### ISSUE TITLE
Checkup week 2

### ISSUE THREAD

**Issue by RobinFrugte97** [NielsPeeters96/real-time-web-2021#1]
Yo Niels!

Je bent al een eindje met je readme, goed dat je je spike hebt opgenomen in je readme.

Dingetjes die je kunt toevoegen aan je readme:
- Een lijstje met features. Kunnen features zijn die je gaat toevoegen, kunnen ook features zijn die je zou willen hebben. Een soort wish list.
- Je zou je socket events kunnen beschrijven in je readme. Hoe gebruik jij socket.io? Wat is serverside en wat is clientside etc.
- Je data life cycle mist nog. Als je die nog niet hebt, zou je die op meerdere manieren kunnen maken. Je kan ervoor kiezen om een soort path uit te stippelen met hoe je applicatie omgaat met data (zie life cycle van [Jonah](https://github.com/theonejonahgold/real-time-web-2021#data-lifecycle)), of je kunt bijvoorbeeld al je socket events beschrijven met de verbindingen tussen client en server (zie life cycle van [Wouter](https://github.com/Mokerstier/real-time-web-1920#dlc-diagram)).
- Je zou kunnen beschrijven hoe je API data eruit ziet en wat je ervan gebruikt.
- Beschrijf alle extra's in je readme. De rubric laat alleen zien hoe je een 5,5 kan halen, het is meer aan jou om te laten zien hoe en waar jij extra tijd hebt besteedt in onderdelen. Neem die extraatjes op in je readme, je hoeft de rubric niet te noemen of te beschrijven, dat doen we bij het eindgesprek.

Succes man!

**Comment by NielsPeeters96** [comment]
Hartstikke bedankt voor je feedback Robin, ga hier mee aan de slag!

**Comment by ralfz123** [comment]
Readme is erg strak, nice!
